version: '3.9'
services:
  api:
    container_name: jwt-api
    build: .
    ports:
      - 8000:8000
    tty: true
    volumes:
      - .:/go/src/jwt-tutorial
    depends_on:
      - db
  db:
    container_name: test_db
    image: postgres:13.3-alpine
    volumes: 
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    container_name: adminer
    image: adminer:4.7.5
    ports:
      - 8080:8080
volumes:
  dbdata: null